name: Package and Upload Helm Chart Release

on:
  push:
    branches:
      - "develop"
    tags:
      - "*"
jobs:
  build:
    name: Package and Upload Helm Chart Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat contrib/helm/charts/aleph/Chart.yaml | grep version | awk '{print $2}')
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Copy existing charts for index regeneration
        run: gsutil -m cp -r gs://bucket-89 . && mv aleph-helm-charts charts

      - name: Package chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            rm -f charts/aleph-${{ steps.get_version.outputs.VERSION }}-dev.tgz
            helm package contrib/helm/charts/aleph --version ${{ steps.get_version.outputs.VERSION }}-dev --destination charts/
      - name: Upload chart to GCS
        run: gsutil cp charts/aleph-${{ steps.get_version.outputs.VERSION }}-dev.tgz gs://bucket-89
      - name: Package chart
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package contrib/helm/charts/aleph --version ${{ steps.get_version.outputs.VERSION }} --destination charts/
      - name: Upload chart to GCS
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: gsutil cp charts/aleph-${{ steps.get_version.outputs.VERSION }}.tgz gs://bucket-89

      - name: Generate index
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo index charts/
      - name: debug
        run: |
          ls charts/
          cat charts/index.yaml
          ls .
      - name: Upload index to GCS
        run: gsutil cp charts/index.yaml gs://bucket-89/index.yaml
